import { Component, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { WorkOrderStore } from '../core/work-order.store';
import { DatePickerComponent } from '../shared/date-picker';

@Component({ standalone: true, imports: [ReactiveFormsModule, DatePickerComponent], template: `<header><p class="page-kicker">Nueva orden</p><h1 class="page-title">Registrá un nuevo trabajo en segundos</h1><p class="page-subtitle">Lo esencial para identificarlo, producirlo y entregarlo.</p></header><section class="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><form [formGroup]="form" (ngSubmit)="submit()" class="surface grid gap-5 p-6 sm:grid-cols-2"><label class="input-label sm:col-span-2">Odontólogo<select formControlName="dentistId"><option value="">Seleccionar odontólogo</option>@for(d of store.dentists;track d.id){<option [value]="d.id">{{d.name}}</option>}</select></label><label class="input-label sm:col-span-2">Paciente / referencia<input formControlName="patientReference" placeholder="Ej. MG"></label><label class="input-label sm:col-span-2">Tipo de trabajo<select formControlName="workTypeId"><option value="">Seleccionar tipo</option>@for(t of store.workTypes;track t.id){<option [value]="t.id">{{t.name}}</option>}</select></label><label class="input-label">Color<input formControlName="color" placeholder="A2"></label><label class="input-label">Fecha de entrega<app-date-picker class="mt-2 block" formControlName="dueDate"/></label><label class="input-label sm:col-span-2">Prioridad<select formControlName="priority"><option value="STANDARD">Estándar</option><option value="URGENT">Urgente</option></select></label><button type="button" (click)="more.set(!more())" class="justify-self-start text-sm font-bold text-blue-700">{{more()?'− Menos información':'+ Más información'}}</button>@if(more()){<label class="input-label">Edad<input formControlName="patientAge" type="number" min="1" max="120" placeholder="Ej. 68"></label><label class="input-label sm:col-span-2">Trabajo a realizar / indicaciones<textarea formControlName="workDescription" rows="4" class="mt-2 w-full rounded-lg border border-slate-300 p-3" placeholder="Ej. Prótesis flexible superior. Cambiar color a A2."></textarea></label>}<button [disabled]="form.invalid" class="button-primary justify-self-start disabled:opacity-50">Crear orden e imprimir etiqueta</button></form><aside class="surface p-5"><p class="section-label">Previsualización de etiqueta</p><p class="mt-3 text-sm text-slate-500">La etiqueta se genera al crear la orden.</p><div class="mt-6 border border-dashed border-slate-300 p-5 text-sm text-slate-500">Seleccioná los datos del trabajo para continuar.</div></aside></section><section class="surface mt-6 p-5"><p class="section-label">Flujo aplicado</p><div class="mt-4 flex flex-wrap gap-2">@for(stage of stages();track stage.id;let i=$index){<span class="rounded-md bg-blue-50 px-2.5 py-1.5 text-xs font-bold text-blue-800">{{i+1}} · {{stage.name}}</span>}</div></section>` })
export class ModernNewOrderPage {
  readonly store=inject(WorkOrderStore); private readonly fb=inject(FormBuilder); private readonly router=inject(Router); readonly more=signal(false);
  readonly form=this.fb.nonNullable.group({dentistId:['',Validators.required],patientReference:['',Validators.required],workTypeId:['',Validators.required],color:[''],dueDate:[new Date(Date.now()+604800000).toISOString().slice(0,10),Validators.required],priority:['STANDARD' as const],patientAge:['', [Validators.min(1),Validators.max(120)]],workDescription:['']});
  readonly stages=computed(()=>{const type=this.store.workTypes.find(t=>t.id===this.form.value.workTypeId);return this.store.workflows.find(w=>w.id===type?.workflowId)?.groups.flatMap(g=>g.stages)??[];});
  submit(){if(this.form.valid){const raw=this.form.getRawValue();const order=this.store.create({...raw,patientAge:raw.patientAge?Number(raw.patientAge):undefined,workDescription:raw.workDescription.trim()||undefined});this.router.navigate(['/orders',order.id]);}}
}
